spring:
  cloud:
    config:
      allow-override: true
      override-none: false

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG

message: "If you're seeing this, global configuration has been applied"
